import React from "react";
import Image from "next/image";
import {
  Stethoscope,
  ClipboardList,
  Pill,
  HeartPulse,
  Info,
  FileDown,
  AlertTriangle,
  ShieldCheck,
} from "lucide-react";

export default function ReportSection({ reportData }: any) {
  if (!reportData) return null;

  // Extract the nested "report" field
  const rawReport = reportData.report;

  if (!rawReport) return null;

  const parsedReport =
    typeof rawReport === "string" ? JSON.parse(rawReport) : rawReport;

  const {
    generatedBy = "",
    generatedOn = "Unknown Date",
    patient = {},
    summary = "",
    symptoms = [],
    diagnosis = {},
    medications = [],
    lifestyleRecommendations = [],
    nextSteps = [],
    disclaimer = "This report is AI-generated based on your input. Please consult a licensed physician before taking any medication.",
  } = parsedReport;

  return (
    <section className="bg-gradient-to-br from-[#e0f7f4] to-[#ccf1ee] sm:py-12 py-6 px-3 md:px-12 rounded-2xl">
      <div className="bg-white rounded-3xl shadow-2xl p-6 md:p-10 border border-gray-100 max-w-5xl mx-auto">
        {/* Section Title */}
        <div className="text-center mb-8">
          <p className="text-[#019c6f] font-medium text-sm uppercase tracking-wide">
            Your Personalized Medical Insight
          </p>
          <h1 className="text-3xl font-bold text-[#0f172a] mt-1">
            Smart AI-Generated Health Report
          </h1>
          <p className="text-sm text-[#475569] mt-2 max-w-md mx-auto">
            Generated by your AI medical consultant after analyzing your
            symptoms, history, and goals. Backed by clinical standards and
            real-time evaluation.
          </p>
        </div>

        {/* Header */}
        <div className="flex items-center justify-between gap-4 mb-8 border-t pt-4">
          <div className="flex items-center gap-4">
            <Image
              src={`/${reportData?.consultant?.image}`}
              alt="AI Consultant"
              width={64}
              height={64}
              className="rounded-full border-2 border-[#019c6f] shadow-md ring-2 ring-[#bbf7d0] p-1"
            />
            <div>
              <div className="flex flex-wrap items-center gap-2 text-xl font-bold text-[#0f172a]">
                <h2 className="whitespace-nowrap">
                  {reportData?.consultant?.name}
                </h2>
                <span className="inline-flex items-center gap-1 text-xs text-[#019c6f] bg-[#e6faf5] px-2 py-1 rounded-full font-medium">
                  <ShieldCheck size={14} /> Trusted AI Report
                </span>
              </div>
              <p className="text-sm text-gray-500 mt-1">
                Generated on: {generatedOn}
              </p>
            </div>
          </div>
        </div>

        {/* Intro */}
        <p className="text-sm text-[#475569] mb-6 leading-relaxed">{summary}</p>

        {/* Patient Info */}
        <div className="bg-[#f1fdfb] rounded-xl p-4 mb-6">
          <div className="flex items-center gap-2 text-[#019c6f] mb-3">
            <ClipboardList size={18} />
            <h3 className="text-sm font-semibold">Patient Summary</h3>
          </div>
          <div className="grid gap-2 text-sm text-[#0f172a]">
            <div className="flex justify-between">
              <span className="font-medium">Patient Name:</span>
              <span>{patient?.name ?? "N/A"}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-medium">Age:</span>
              <span>{patient?.age ?? "N/A"}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-medium">Gender:</span>
              <span>{patient?.gender ?? "N/A"}</span>
            </div>
          </div>
        </div>

        {/* Symptoms */}
        {symptoms.length > 0 && (
          <div className="mb-6">
            <div className="flex items-center gap-2 text-[#019c6f] mb-2">
              <AlertTriangle size={18} />
              <h3 className="text-md font-semibold">Symptoms Reported</h3>
            </div>
            <ul className="list-disc pl-5 text-sm text-[#475569] space-y-1 bg-gray-50 p-4 rounded-xl">
              {symptoms.map((symptom, index) => (
                <li key={index}>{symptom}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Diagnosis */}
        {diagnosis?.condition && (
          <div className="mb-6">
            <div className="flex items-center gap-2 text-[#019c6f] mb-2">
              <Stethoscope size={18} />
              <h3 className="text-md font-semibold">Diagnosis</h3>
            </div>
            <p className="text-sm text-[#475569] bg-gray-50 p-4 rounded-xl leading-relaxed">
              <strong>{diagnosis.condition}</strong>: {diagnosis.details}
            </p>
          </div>
        )}

        {/* Medications */}
        {medications.length > 0 && (
          <div className="mb-6">
            <div className="flex items-center gap-2 text-[#019c6f] mb-2">
              <Pill size={18} />
              <h3 className="text-md font-semibold">Prescribed Medications</h3>
            </div>
            <ul className="list-disc pl-5 text-sm text-[#475569] space-y-1 bg-gray-50 p-4 rounded-xl">
              {medications.map((med, index) => (
                <li key={index}>
                  {med.name} {med.dosage} – {med.instructions}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Lifestyle Recommendations */}
        {lifestyleRecommendations.length > 0 && (
          <div className="mb-6">
            <div className="flex items-center gap-2 text-[#019c6f] mb-2">
              <HeartPulse size={18} />
              <h3 className="text-md font-semibold">
                Lifestyle Recommendations
              </h3>
            </div>
            <ul className="list-disc pl-5 text-sm text-[#475569] space-y-1 bg-gray-50 p-4 rounded-xl">
              {lifestyleRecommendations.map((tip, index) => (
                <li key={index}>{tip}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Next Steps */}
        {nextSteps.length > 0 && (
          <div className="bg-[#f1fdfb] rounded-xl p-4 mb-6">
            <div className="text-[#019c6f] font-semibold mb-2">Next Steps</div>
            <ul className="list-disc pl-5 text-sm text-[#475569] space-y-1">
              {nextSteps.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Download Button */}
        <div className="text-center mt-6">
          <button className="flex items-center gap-2 bg-[#019c6f] hover:bg-[#017a59] text-white px-5 py-2 rounded-full text-sm mx-auto">
            <FileDown size={16} /> Download Full Report
          </button>
        </div>

        {/* Disclaimer */}
        <div className="flex items-center gap-2 text-xs text-gray-400 border-t pt-4 mt-8">
          <Info size={16} />
          <p>{disclaimer}</p>
        </div>
      </div>
    </section>
  );
}
